// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_VTmBaZxg1WPp8UQvi3W8c6vbSYrKpSc',
    appId: '1:888457608412:web:6b10ab73f6fda1a5ce4819',
    messagingSenderId: '888457608412',
    projectId: 'flutter-project-d7ba2',
    authDomain: 'flutter-project-d7ba2.firebaseapp.com',
    storageBucket: 'flutter-project-d7ba2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Fjc2IRkk6DsqYs8CrCIu1xgQDJ4SqA0',
    appId: '1:888457608412:android:f1048ef05a86d436ce4819',
    messagingSenderId: '888457608412',
    projectId: 'flutter-project-d7ba2',
    storageBucket: 'flutter-project-d7ba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhS-YdnLKkjooKYQY3TS-edS0MlMpyB6c',
    appId: '1:888457608412:ios:8117580e5d7894adce4819',
    messagingSenderId: '888457608412',
    projectId: 'flutter-project-d7ba2',
    storageBucket: 'flutter-project-d7ba2.appspot.com',
    iosBundleId: 'com.example.curdFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhS-YdnLKkjooKYQY3TS-edS0MlMpyB6c',
    appId: '1:888457608412:ios:8117580e5d7894adce4819',
    messagingSenderId: '888457608412',
    projectId: 'flutter-project-d7ba2',
    storageBucket: 'flutter-project-d7ba2.appspot.com',
    iosBundleId: 'com.example.curdFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_VTmBaZxg1WPp8UQvi3W8c6vbSYrKpSc',
    appId: '1:888457608412:web:1bd5776ee2490041ce4819',
    messagingSenderId: '888457608412',
    projectId: 'flutter-project-d7ba2',
    authDomain: 'flutter-project-d7ba2.firebaseapp.com',
    storageBucket: 'flutter-project-d7ba2.appspot.com',
  );
}